# Generated by Django 4.2.20 on 2025-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="date",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="title",
        ),
        migrations.AddField(
            model_name="experience",
            name="outils",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="experience",
            name="periode",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="experience",
            name="poste",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="education",
            name="ecole",
            field=models.TextField(max_length=200),
        ),
    ]
