# Generated by Django 4.2.20 on 2025-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_experience_date_remove_experience_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="lieu",
            field=models.CharField(default="", max_length=200),
        ),
    ]
