# Generated by Django 4.2.20 on 2025-03-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detailproject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("dossier_images", models.TextField(default="", max_length=200)),
                (
                    "number_projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.project"
                    ),
                ),
            ],
        ),
    ]
