# Generated by Django 4.2.20 on 2025-03-19 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_detailproject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailproject",
            old_name="number_projet",
            new_name="projet",
        ),
    ]
