# Generated by Django 4.2.20 on 2025-03-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_rename_number_projet_detailproject_projet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailproject",
            name="dossier_images",
            field=models.CharField(default="", max_length=200),
        ),
    ]
