# Generated by Django 4.2.20 on 2025-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_detailproject_dossier_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detailproject",
            old_name="description",
            new_name="objectifs",
        ),
        migrations.AddField(
            model_name="detailproject",
            name="donnees",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="detailproject",
            name="experimentations",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="detailproject",
            name="pretraitement",
            field=models.TextField(default=""),
        ),
    ]
